### ISSUE TITLE
Restore from backup (ansible) --> Timeouts

### ISSUE THREAD

**Issue by AdamStawarz** [scylladb/scylla-manager#2928]
I'm trying restore from backup following this method:
https://github.com/scylladb/scylla-manager/tree/master/ansible/restore
but I am dealing with timeout's:

#### Issue:
```
TASK [Wait for CQL port] *****************************************************************************************************************************************************
fatal: [x.x.x.x]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for 127.0.0.1:9042"}

```
netstat -tulpn
tcp        0      0 172.16.1.234:9042       0.0.0.0:*               LISTEN      -

#### Resolution:
we shouldn't care about localhost but listen on external IP so something like:
   ```
 - name: Wait for CQL port
      wait_for:
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        port: 9042
```
