### ISSUE TITLE
docs: sctool, support for multiple examples

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/scylla-manager#3010]
## Motivation

We could support for more than one example per command. For example, instead of:

```
example: |
  sctool status -c prod-cluster
  Datacenter: eu-west
```

The example key could look like this:

```
examples: 
   - name: Example A 
      description: Example description
     command: sctool xyz
   - name: Example B
      description: Example description
     command: sctool xyz
```

In addition, adding the new keys ``name`` and ``description`` will also be possible to format commands as code-blocks and descriptions as regular text.

## Proposal

- [ ] Update sctool doc generator to support multiple examples
- [ ] Update the docs template to render multiple examples

## Implementation

While I can help editing [command.tmpl](https://github.com/scylladb/scylla-manager/blob/master/docs/source/_templates/command.tmpl), I'd appreciate it if someone could modify the ``sctool docs`` command to support multiple examples.
