### ISSUE TITLE
Issue in page Restore

### ISSUE THREAD

**Issue by noellymedina** [scylladb/scylla-manager#3021]
Update the path to the relevant Doc page: https://manager.docs.scylladb.com/branch-2.5/restore/index.html#playbook-parameters
(Fits for all the versions of the same page)

Problem
The step is not explicit enough on this part related to `vars.yaml`, causing confusion to the user when editing this file.

Suggest a fix
We could add something like:
**IPs of the destination cluster map to UUIDs of nodes of the source cluster.**

On top of that providing a proper example that includes a source and destination clusters description + the corresponding vars.yaml in the Doc page would complete the picture.
e.g:
Source cluster:
```
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens       Owns    Host ID                               Rack
UN  10.240.0.6   119.6 MB   256          ?       9b6b5206-63c8-4cdf-9b4f-23e37977fd14  rack1
UN  10.240.0.93  122.69 MB  256          ?       2d8045e7-51a4-42c4-bb8f-5e8aa77a8228  rack1
```
Destination cluster:
```
Datacenter: us-east1
====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens       Owns    Host ID                               Rack
UN  75.196.92.133  122.14 MB  256          ?       a21b38b4-c0b1-49f0-89f2-931fe027d6b0  b
UN  75.237.179.49  121.22 MB  256          ?       a0a63682-95e3-4cf3-9f46-4d551bd7eba2  b
```
The `vars.yaml` would look like:
```
# backup_location specifies the location parameter used in Scylla Manager
# when scheduling a backup of a cluster.
backup_location: gcs:manager-bucket 

# snapshot_tag specifies the Scylla Manager snapshot tag you want to restore.
snapshot_tag: sm_20220204002134UTC

# host_id specifies a mapping from the clone cluster node IP to the source
# cluster host IDs.
host_id:
  75.237.179.49: 9b6b5206-63c8-4cdf-9b4f-23e37977fd14
  75.196.92.133: 2d8045e7-51a4-42c4-bb8f-5e8aa77a8228
# destination IP: source ID
```
The `hosts` file would look like:
```
75.237.179.49
75.196.92.133
```

Cc. @vladzcloudius @tzach
