### ISSUE TITLE
Scylla manager couldn't start in GKE autopilot

### ISSUE THREAD

**Issue by l1nknyto** [scylladb/scylla-manager#3122]
Hi guys,

I am trying to install scylla in GKE autopilot. I am follow the installation using helm.
Here's the step that I do:
1. Install cert-manager
2. Install scylla-operator
    `helm upgrade --install scylla-operator scylla/scylla-operator --values values.operator.yaml --create-namespace --namespace scylla-`operator
3. Install scylla
    `helm upgrade --install scylla scylla/scylla --values values.cluster.yaml --create-namespace --namespace scylla`
4. Install scylla-manager
    `helm upgrade --install scylla-manager scylla/scylla-manager --values values.manager.yaml --create-namespace --namespace scylla-manager`

I've try to switch the order between step 3 and 4, but the scylla-manager couldn't start.
When I look at the log in scylla-manager, there are some error:
```
2022-04-19T03:58:03.871485480Z {L: ERROR, M: Bye, T: 2022-04-19T03:58:03.871Z, _trace_id: xXXBYXq4QMKTFt_dfoM2LA, error: no connection to database, make sure Scylla server is running and that database section in config file(s) /mnt/etc/scylla-manager/scylla-manager.yaml is set correctly: giving up after 60 attempts: dial tcp 10.1…
2022-04-19T03:58:03.871586912Z STARTUP ERROR: no connection to database, make sure Scylla server is running and that database section in config file(s) /mnt/etc/scylla-manager/scylla-manager.yaml is set correctly: giving up after 60 attempts: dial tcp 10.11.....212:9042: i/o timeout
```

I look around in scylla-operator log and found this:
```
2022-04-19T00:50:12.714321601Zsyncing key 'scylla/scylla' failed: can't create StatefulSet(s): can't create missing statefulset: admission webhook "policycontrollerv2.common-webhooks.networking.gke.io" denied the request: GKE Policy Controller rejected the request because it violates one or more policies: {"[denied by autogke-default-linux-capabilities]":["linux capability 'SYS_NICE' on container 'scylla' not allowed; Autopilot only allows the capabilities: 'AUDIT_WRITE,CHOWN,DAC_OVERRIDE,FOWNER,FSETID,KILL,MKNOD,NET_BIND_SERVICE,NET_RAW,SETFCAP,SETGID,SETPCAP,SETUID,SYS_CHROOT,SYS_PTRACE'. Requested by user: 'system:serviceaccount:scylla-operator:scylla-operator', groups: 'system:serviceaccounts,system:serviceaccounts:scylla-operator,system:authenticated'."]}
```
Seem this related with gke autopilot permission.
Anyone has idea how to solve it? Thanks in advance

This is the GKE version used:
```
NAME: gk3-autopilot-cluster
VERSION: v1.21.9-gke.1002 
OS-IMAGE: Container-Optimized OS from Google
KERNEL-VERSION: 5.4.170+
CONTAINER-RUNTIME: containerd://1.4.8
```

values.manager.yaml:
```
# Scylla Manager image
#image:
#  tag: 2.3.0

# Resources allocated to Scylla Manager pods
resources:
  requests:
    cpu: 200m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 256Mi
# Resources allocated to Scylla Manager Controller pods
controllerResources:
  requests:
    cpu: 200m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Scylla instance for Manager
scylla:
  developerMode: true
  #scyllaImage:
  #  tag: 4.5.1
  #agentImage:
  #  tag: 2.5.2
  datacenter: asia-southeast2
  racks:
    - name: asia-southeast2-a
      members: 1
      storage:
        capacity: 5Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 1Gi

```

values.operator.yaml:
```
# Operator replicas use leader election. Setting to 1 will disable pdb creation
# and won't be HA; creations or updates of Scylla CRs will fail during operator
# upgrades or disruptions
replicas: 2

# Specify desired Scylla Operator image
#image:
#  tag: 1.7.2

# Resources allocated to Scylla Operator pods
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

webhook:
  createSelfSignedCertificate: true
  certificateSecretName: ""

```
