### ISSUE TITLE
Minio Backups Fail on Metadata Operations during Purge

### ISSUE THREAD

**Issue by steve-gray** [scylladb/scylla-manager#3164]
During backups using Minio it appears to fail/catch fire during the processing of N day retention. It seems similar to, but somehwat different from the problem in https://github.com/scylladb/scylla-operator/issues/950 

# Environment
- Scylla 4.6.3
- Operator 2.6.3
- Manager 1.7.2

All nodes registered fine in operator.
![image](https://user-images.githubusercontent.com/14563775/169909202-4edeaaae-6dd6-433e-bceb-96abdb43837f.png)

# What Happens
Backups run as expected, but during the retention processing they fail with a metadata error.

![image](https://user-images.githubusercontent.com/14563775/169909114-260dee95-cd46-4ea5-b908-1c5b83252cb4.png)

All three nodes participating in the backup fail with the same error:

```
 10.202.17.92: find and load remote manifests: reading manifest backup/meta/cluster/02ec0721-c951-42ec-98d4-5e2e644b6d28/dc/oracle-sydney/node/4cfd1669-bc5d-4ea0-97aa-4f44b27ce4fd/task_a28ad9e7-65a9-4e44-a2a1-59526d175099_tag_sm_20220523111740UTC_manifest.json.gz: load manifest backup/meta/cluster/02ec0721-c951-42ec-98d4-5e2e644b6d28/dc/oracle-sydney/node/4cfd1669-bc5d-4ea0-97aa-4f44b27ce4fd/task_a28ad9e7-65a9-4e44-a2a1-59526d175099_tag_sm_20220523111740UTC_manifest.json.gz: giving up after 10 attempts: invalid character '\x1f' looking for beginning of value
```

Downloading the file from the bucket and inspecting reveals its perfectly valid JSON/passes linting checks etc:

![image](https://user-images.githubusercontent.com/14563775/169909436-d97b0a29-6adc-4643-9f4b-d9765f7ad78c.png)

# Scylla Agent Configuration
Injected via secret in Terraform:
```
s3:
  access_key_id: ${local.storage_pool_scylla_manager_key_name}
  secret_access_key: ${random_password.storage_scylla_manager_secret.result}
  provider: Minio
  endpoint: http://${local.storage_pool_scylla_manager_tenant}-hl.${local.namespace_name_scylla_manager}:9000
```
