### ISSUE TITLE
failed repairs on dev clusters

### ISSUE THREAD

**Issue by SergeiMalkov** [scylladb/scylla-manager#3251]
# Installations details

```yaml
Scylla Cloud, production environment
Affected Clusters: 4252, 4253, 6467, 7269
Scylla Manager versions:
  Clusters 4252, 6467, 726:
    Client version: 2.6.3-0.20220307.89b222a1a68
    Server version: 2.6.3-0.20220307.89b222a1a68
  
  Cluster 4253:
    Client version: 3.0.0-0.20220523.5501e5d7f53
    Server version: 3.0.0-0.20220523.5501e5d7f53
```

# Abstract

Repairs fail with the following error: "optimize small tables: fetch table disk size report: shard count: giving up after 3 attempts: agent [HTTP 502] cannot read response: unexpected end of JSON input".
I can't understand where does this error come from and error messages and logs entries aren't of a great help for me. The following issue is divided into two chapters for corresponding version of Scylla Manager version.
I need to upgrade customer's clusters from 2.6.3 to 3.0.0, but the upgrade itself doesn't address the issue.
