### ISSUE TITLE
Too many backups are started

### ISSUE THREAD

**Issue by Mokto** [scylladb/scylla-manager#3328]
Backups seem to be a non stop process even though I chose a period of 6.5h:

<img width="911" alt="Screenshot 2023-03-17 at 05 35 05" src="https://user-images.githubusercontent.com/5103928/225813610-0c82af26-e436-4cdd-ae53-3126029060a0.png">

<img width="344" alt="image" src="https://user-images.githubusercontent.com/5103928/225813969-e501e6ba-8752-49b9-acc1-53225bd853e6.png">

This is how i create the backup in the yaml file (i'm using scylladb operator)

```
  backups:
  - name: "full backup"
    rateLimit: ["50"]
    numRetries: 3
    retention: 6
    startDate: now
    location: ["gcs:mybucketname"]
    interval: "0d6h30m0s"
    keyspace: ["keyspace1", "production"]
```

**Versions:**
Scylladb: 5.1.6
Operator version 1.8.0
Manager: 3.2-dev-0.20230315.8cf611cd-SNAPSHOT-8cf611cd (also tried with 3.1.0-rc0-0.20230315.88bcedf5 and 3.0.0)

Thanks a lot!
