### ISSUE TITLE
Backup failure : S3 permission for Service Account? 

### ISSUE THREAD

**Issue by brickpattern** [scylladb/scylla-manager#3618]
Environment : AWS EKS latest version
Scylla-Operation : v11 
Scylla-Manager : using manager.yaml found in  examples/common of Scylla-Operator. 

In the cluster definition , following spec was used . I only specified the bucket name.

```
spec:
  agentRepository: docker.io/scylladb/scylla-manager-agent
  agentVersion: latest
  backups:
  - interval: 1d
    keyspace:
    - observations
    location:
    - s3:rc-scylla-cluster
    name: daily users backup
    numRetries: 3
    rateLimit:
    - "50"
    retention: 3
    startDate: now
  - interval: 7d
    location:
    - s3:rc-scylla-cluster
    name: weekly full cluster backup
    numRetries: 3
    rateLimit:
    - "50"
    retention: 3
    startDate: now
```

Error: 
```

{"L":"INFO","T":"2023-10-24T21:41:26.507Z","N":"cluster.client","M":"HTTP","host":"10.100.24.13:10001","method":"POST","uri":"/agent/rclone/operations/check-permissions","duration":"403ms","status":400,"bytes":322,"dump":"HTTP/1.1 400 Bad Request\r\nContent-Length: 322\r\nContent-Type: application/json\r\nDate: Tue, 24 Oct 2023 21:41:26 GMT\r\n\r\n{\"input\":{\"fs\":\"s3:pw-rc-scylla-cluster\"},\"message\":\"no put permission: s3 upload: 301 Moved Permanently: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (code:PermanentRedirect)\",\"path\":\"operations/check-permissions\",\"status\":400}\n","_trace_id":"pb_ZxkH_R-iga_Ccd_TyuQ"}
{"L":"INFO","T":"2023-10-24T21:41:26.507Z","N":"backup","M":"Location check FAILED","host":"10.100.24.13","location":"s3:rc-scylla-cluster","error":"agent [HTTP 400] no put permission: s3 upload: 301 Moved Permanently: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (code:PermanentRedirect)","_trace_id":"pb_ZxkH_R-iga_Ccd_TyuQ"}
{"L":"ERROR","T":"2023-10-24T21:41:26.507Z","N":"backup","M":"Failed to access location from node","node":"10.100.24.13","location":"s3:rc-scylla-cluster","error":"10.100.24.13: agent [HTTP 400] no put permission: s3 upload: 301 Moved Permanently: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (code:PermanentRedirect) - make sure the location is correct and credentials are set, to debug SSH to 10.100.24.13 and run \"scylla-manager-agent check-location -L s3:pw-rc-scylla-cluster --debug\"","_trace_id":"pb_ZxkH_R-iga_Ccd_TyuQ","errorStack":"github.com/scylladb/scylla-manager/v3/pkg/service/backup.(*Service).checkHostLocation\n\tgithub.com/scylladb/scylla-manager/v3/pkg/service/backup/service.go:378\n
```

The role "scylla-manager" has been annotated withe a ROLE that has full perm to S3 (default AWS permission for testing).

Q -  Why does scylla-manager fail? Is the (default) service account scylla-manager the correct  SA to grant permissions to the S3 bucket ? 
Q - is the S3 bucket location need to be formatted any differently? the documentation has the format of "S3:bucket-name"
