### ISSUE TITLE
Give a possibility to override default CQL port for scylla-manager's DB

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3635]
As per topic.
There is no option to use other than default (9042) CQL port for the scylla-manager's DB.
https://manager.docs.scylladb.com/stable/install-scylla-manager.html#configure-storage

We'd like to introduce the option that makes it possible.

```
database:
  hosts:
    - 127.0.0.1
  port: <value>      <--- to be added
```
