### ISSUE TITLE
Unable to set startDate for periodic repair task via helm chart.

### ISSUE THREAD

**Issue by artashsct** [scylladb/scylla-manager#3639]
Hello, 

It seems there's an incompatibility between `sctool` commands and the helm chart `repairs` block variables.
`sctool` documentation is noting as deprecated `startDate` and `interval` commands and suggesting to use `cron` and `window` instead, but the latter are not supported by helm chart.

So in order to set a periodic repair i'm using `startDate` and `interval` fields in repairs block. To set, lets say, a weekly periodic repair at midnight i'm using this

```
# Scylla Manager Repair task definition
repairs:
  - name: "weekly repair"
    intensity: "2"
    interval: "7d"
    dc: ["dc1"]
    startDate: "now+6h" // assuming the apply time is 18:00 UTC
```

The issue is that recent scylla manager versions are applying this settings periodically, with some interval on existing initial task and modifying the start date because of `now` keyword, which results to a rescheduling of  periodic task and actual repair never happens. 

When i'm setting the `startDate` in RFC3339 standard its working the first time, but because of reapplication of periodic task it eventually resulting an error in scylla-manager:

`E1118 13:54:36.459262       1 manager/controller.go:150] syncing key 'scylla/scylla' failed: runSync repair tasks: transform to manager task: parse start date: start date cannot be in the past`

So one available option for helm chart is not to use the `startDate`  and use only the `interval`, without possibility of setting the start date (do it manually at midnight).

Maybe i'm missing something? Any help will be appreciated.

Thanks.
