### ISSUE TITLE
scyllamgr_setup is missing CQL credential options

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-manager#3680]
Version: 3.2

*Description*
Since version 3.2 (?) it's important to provide the managed cluster CQL credentials if one wants to benefit from certain repair optimization (which is actually more than just an optimization - you really want to repair a base before the MV in order to avoid creation of MV getting out of sync as a result, right @asias @raphaelsc @nyh?).

Unless I'm wrong about the importance of the repair order the corresponding piece in the SM documentation is not clear enough about it: https://manager.docs.scylladb.com/stable/repair/index.html 
(There is a small and insignificant note at the end of the very long page above).

And most importantly there is zero automation of the corresponding configuration.
It makes sense to add corresponding keys to the `scyllamgr_setup` and make it configure relevant parts of the `scylla-manager.yaml`:

```
database:
  hosts:
    - <contact point 1>
    - <contact point 2>
  user: <CQL User name>
  password: <password>
```
