### ISSUE TITLE
Scylla Manager should fallback to non-SSL port when client doesn't require authentication

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3763]
Introduced in 3.2.6.

Scylla configuration:
```
client_encryption_options:
  enabled: true
  require_client_auth: False
```

Makes the client auth optional. Scylla manager should fallback to non-SSL port when creating the CQL session.
Now, it can be achieved by using `--force-TLS-disabled` flag, but the default behavior shouldn't be broken.
Default behavior is, that in such a situation, manager must fallback to non-SSL.

**Comment by Michal-Leszczynski** [comment]
@karol-kokoszka But why can't we change the default behavior of some internal procedure if it does not break backward compatibility and increases security? Especially that it can be turned off with mentioned flag that was created for this reason. Note that if we change the current behavior to the old one, there is no way to use TLS encryption without authentication anymore.

From my perspective, current behavior should stay as it was agreed before (https://github.com/scylladb/scylla-manager/pull/3699#issuecomment-1912108430) and for reasons mentioned above.

**Comment by karol-kokoszka** [comment]
@Michal-Leszczynski I think you're right.

We changed the default behavior, and cloud reported bug right after where they couldn't restore cluster with manager 3.2.6.
By default, cloud uses the following configuration:
```
client_encryption_options:
  enabled: true
  certificate: /etc/scylla/server.crt
  keyfile: /etc/scylla/server.key
native_shard_aware_transport_port: 19042
native_transport_port: 9042
native_shard_aware_transport_port_ssl: 19142
native_transport_port_ssl: 9142
```

One of the test where they restore the cluster didn't work and it was a blocker for a release of new scylla-cloud.
It was failing on session creation with error regarding TLS. Looks that we wanted to establish the secured connection, but it was refused. But, frankly speaking, it doesn't mean that there is something wrong with the way how SM behaves.
It started to work fine only when "--force-tls-disabled" was used. We may have some problem in cloud actually.

I'm closing this issue.
Default configuration like that is supposed to use SSL port always.
