### ISSUE TITLE
sctool: cluster requires CQL authentication but username/password was not set

### ISSUE THREAD

**Issue by rwnd-bradley** [scylladb/scylla-manager#3804]
I am running the scylla helm stack in kubernetes (scylla-operator, scylla-manager, scylla), I have automated backups with s3 that are working. When I try to use the sctool restore command on my cluster, I cannot due to the following error (command is minimal to reproduce, other arguments do not change the outcome):

```
scylla@scylla-manager-77dd86f7b9-zxmhq:/$ sctool restore -c scylla/scylla --location s3:scylla-backup --dry-run
Error: get restore target, units and views: create worker: get CQL cluster session: cluster requires CQL authentication but username/password was not set
```

I do have the password authenticator enabled on the scylla cluster:

```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-config
  namespace: scylla
data:
  scylla.yaml: |
    authenticator: PasswordAuthenticator
    authorizer: CassandraAuthorizer
```

so I assume that scylla-manager requires some cql user credentials? if this is so, I cannot find any documentation regarding it, please advise.

scylla version: 5.4.5
scylla agent version: 3.2.7
scylla manager version: 3.2.7
scylla operator version: 1.12
