### ISSUE TITLE
Enable Scylla encryption (if disabled) for Manager SCT tests

### ISSUE THREAD

**Issue by mikliapko** [scylladb/scylla-manager#4164]
Scope:
1. Check if current SCT tests for Manager run with enabled Scylla encryption.
2. If not, make it enabled by default.

**Comment by mikliapko** [comment]
Currently, for Manager tests we configure `scylla.yaml` in a next way:
- enabled **client encryption**
```
client_encryption_options:
  certificate: /etc/scylla/ssl_conf/client-facing.crt
  enabled: true
  keyfile: /etc/scylla/ssl_conf/client-facing.key
  truststore: /etc/scylla/ssl_conf/ca.pem
```
- enabled **EaR**
```
kms_hosts:
  auto:
    aws_region: us-east-1
    aws_use_ec2_credentials: true
    master_key: alias/testid-68565fdc-a174-463f-aba0-1b77ad4d56f4
system_info_encryption:
  enabled: true
  key_provider: KmsKeyProviderFactory
  kms_host: auto
user_info_encryption:
  enabled: true
  key_provider: KmsKeyProviderFactory
  kms_host: auto
```

It looks like we are missing [server encryption](https://opensource.docs.scylladb.com/stable/operating-scylla/security/node-node-encryption.html) only. Can it be important for Manager to have it enabled as well?
@karol-kokoszka @Michal-Leszczynski @VAveryanov8
